In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [131]:
df = pd.read_csv('phones_data_after_preprocessing.csv')

In [132]:
df1= df.drop(['Unnamed: 0'], axis=1)
df1.head()

brand_name                                    model_name       os  \
0    ALCATEL          1 1/8GB Bluish Black (5033D-2JALUAA)  Android   
1    ALCATEL  1 5033D 1/16GB Volcano Black (5033D-2LALUAF)  Android   
2    ALCATEL  1 5033D 1/16GB Volcano Black (5033D-2LALUAF)  Android   
3    ALCATEL  1 5033D 1/16GB Volcano Black (5033D-2LALUAF)  Android   
4      Nokia                           1.3 1/16GB Charcoal  Android   

   popularity  best_price  lowest_price  highest_price  sellers_amount  \
0         422      878800     456976000      456976000              36   
1         323      937560     487531200      487531200              36   
2         299      937560     487531200      487531200              36   
3         287      937560     487531200      487531200              36   
4        1047     1039480     540529600      540529600              10   

   screen_size  memory_size  battery_size release_date  cluster  
0         5.00            8          2000      10-2020        1  
1         5.00           16          2000       9-2020        1  
2         5.00           16          2000       9-2020        1  
3         5.00           16          2000       9-2020        1  
4         5.71           16          3000       4-2020        1

In [133]:
X=df1.iloc[:, [4, 9]].values
Y=df1.iloc[:, [0,1,2,3,5,6,7,8,10,11,12]].values

In [134]:
X

array([[ 878800,       8],
       [ 937560,      16],
       [ 937560,      16],
       ...,
       [4578080,     128],
       [9752600,     128],
       [ 471640,      95]], dtype=int64)

In [135]:
Y

array([['ALCATEL', '1 1/8GB Bluish Black (5033D-2JALUAA)', 'Android',
        ..., 2000, '10-2020', 1],
       ['ALCATEL', '1 5033D 1/16GB Volcano Black (5033D-2LALUAF)',
        'Android', ..., 2000, '9-2020', 1],
       ['ALCATEL', '1 5033D 1/16GB Volcano Black (5033D-2LALUAF)',
        'Android', ..., 2000, '9-2020', 1],
       ...,
       ['HUAWEI', 'nova 5T 6/128GB Black (51094MEU)', 'Android', ...,
        3750, '11-2019', 1],
       ['ZTE', 'nubia Red Magic 5G 8/128GB Black', 'Android', ..., 4500,
        '10-2020', 0],
       ['Sigma mobile', 'x-style 35 Screen', 'Other', ..., 1750,
        '1-2020', 1]], dtype=object)

In [136]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0) 

In [137]:
X_train

array([[ 2002000,       64],
       [ 3760120,      128],
       [ 3676920,      128],
       ...,
       [10290800,       64],
       [ 2842840,       64],
       [ 2750800,       64]], dtype=int64)

In [138]:
Y_train

array([['LG', 'G6 64GB Black (LGH870DS.ACISBK)', 'Android', ..., 3300,
        '3-2017', 1],
       ['Xiaomi', 'Pocophone F1 6/128GB Blue', 'Android', ..., 4000,
        '8-2018', 1],
       ['Motorola', 'One Fusion+ 6/128GB Blue (PAJW0006RS)', 'Android',
        ..., 5000, '9-2020', 1],
       ...,
       ['Apple', 'iPhone XS 64GB Space Gray (MT9E2)', 'iOS', ..., 2568,
        '9-2018', 0],
       ['Oukitel', 'K9 4/64 Black', 'Android', ..., 6000, '7-2019', 1],
       ['Motorola', 'One Power XT1942-1 4/64GB Dual Sim Black',
        'Android', ..., 5000, '3-2019', 1]], dtype=object)

In [146]:
X_test

array([[ 5706480,      128],
       [ 5649800,       64],
       [ 1660360,       64],
       [ 8759400,      128],
       [  810160,       95],
       [ 3216720,       64],
       [ 2011880,       32],
       [ 2171000,       16],
       [ 1644240,       32],
       [ 8734960,      128],
       [ 7523360,      128],
       [ 8734960,      128],
       [  344760,        0],
       [  340600,       95],
       [ 2057640,       64],
       [ 1143480,       16],
       [ 1346800,       32],
       [ 2936960,      128],
       [18817760,      512],
       [ 1460680,       64],
       [28775760,      256],
       [  268840,        0],
       [ 8062600,      128],
       [  662480,        0],
       [ 1622920,       32],
       [  963040,       16],
       [ 1945840,       32],
       [ 2178280,       32],
       [ 3719040,      128],
       [11089520,      128],
       [ 4700280,       64],
       [10925720,      128],
       [ 3380000,       16],
       [ 2547480,       64],
       [ 10228

In [147]:
Y_test

array([['OPPO', 'Reno4 Z 5G 8/128GB Black', 'Android', ..., 4000,
        '10-2020', 0],
       ['Honor', '10 6/64GB Black', 'Android', ..., 3400, '6-2018', 0],
       ['Tecno', 'Spark 6 Go KE5j 3/64GB Aqua Blue (4895180762918)',
        'Android', ..., 5000, '11-2020', 1],
       ...,
       ['Nokia', '105 Dual Sim New Black (A00028315)', 'Other', ..., 800,
        '9-2017', 1],
       ['Apple', 'iPhone XS Max 256GB Gold (MT552)', 'iOS', ..., 3174,
        '9-2018', 0],
       ['Samsung', 'Galaxy M10S M107F 3/32GB Black', 'Android', ...,
        4000, '4-2020', 1]], dtype=object)

In [139]:
from sklearn.cluster import KMeans

In [140]:
# Menjalankan K-Means Clustering ke dalam dataset
kmeans = KMeans(n_clusters = 3, init = 'k-means++', random_state = 42)
y_true=kmeans.fit_predict(X_train, Y_train)
y_true

array([1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 2, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       0, 1, 2, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 0, 1, 2, 1, 2, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 2, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 2, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 2, 1, 0, 1, 1, 1, 1, 1, 2, 2, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 2, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1,

In [141]:
kmeans = KMeans(n_clusters = 3, init = 'k-means++', random_state = 42)
y_pred=kmeans.fit_predict(X_test)
y_pred

array([0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 2, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 2, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 2, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 2, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1])

In [142]:
np.sum(y_true)

868

In [143]:
np.sum(y_pred)

218

In [144]:
from sklearn.metrics import accuracy_score
print('Accuracy score: ', accuracy_score(y_pred, y_test))

Accuracy score:  1.0


In [145]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred, y_test)

array([[ 42,   0,   0],
       [  0, 188,   0],
       [  0,   0,  15]], dtype=int64)

In [154]:
from sklearn.metrics import classification_report
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        42
           1       1.00      1.00      1.00       188
           2       1.00      1.00      1.00        15

    accuracy                           1.00       245
   macro avg       1.00      1.00      1.00       245
weighted avg       1.00      1.00      1.00       245

